-- MySQL Script generated by MySQL Workbench
-- Mon Jun 27 08:52:08 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dadosVendas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dadosVendas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dadosVendas` DEFAULT CHARACTER SET utf8 ;
USE `dadosVendas` ;

-- -----------------------------------------------------
-- Table `dadosVendas`.`tipoDoCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dadosVendas`.`tipoDoCliente` (
  `idTipoDoCliente` INT NOT NULL AUTO_INCREMENT,
  `profissao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoDoCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dadosVendas`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dadosVendas`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nomeCliente` VARCHAR(45) NOT NULL,
  `telefone` DECIMAL(9) NOT NULL,
  `fkTipoDoCliente` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fkTipoDoCliente_idx` (`fkTipoDoCliente` ASC) VISIBLE,
  CONSTRAINT `fkTipoDoCliente`
    FOREIGN KEY (`fkTipoDoCliente`)
    REFERENCES `dadosVendas`.`tipoDoCliente` (`idTipoDoCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dadosVendas`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dadosVendas`.`Aluno` (
  `idAluno` INT NOT NULL AUTO_INCREMENT,
  `nomeAluno` VARCHAR(45) NOT NULL,
  `periodo` VARCHAR(45) NOT NULL,
  `curso` VARCHAR(45) NOT NULL,
  `professor` VARCHAR(45) NOT NULL,
  `fkCliente` INT NOT NULL,
  PRIMARY KEY (`idAluno`),
  INDEX `fkCliente_idx` (`fkCliente` ASC) VISIBLE,
  CONSTRAINT `fkCliente`
    FOREIGN KEY (`fkCliente`)
    REFERENCES `dadosVendas`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dadosVendas`.`Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dadosVendas`.`Venda` (
  `idVenda` INT NOT NULL,
  `dataVenda` DATETIME(8) NOT NULL,
  `valor` FLOAT NOT NULL,
  `pago?` TINYINT(3) NOT NULL,
  `fkCliente` INT NOT NULL,
  PRIMARY KEY (`idVenda`),
  INDEX `fkCliente_idx` (`fkCliente` ASC) VISIBLE,
  CONSTRAINT `fkCliente`
    FOREIGN KEY (`fkCliente`)
    REFERENCES `dadosVendas`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dadosVendas`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dadosVendas`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nomeProduto` VARCHAR(45) NOT NULL,
  `valorProduto` FLOAT NOT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dadosVendas`.`itensVendidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dadosVendas`.`itensVendidos` (
  `iditensVendidos` INT NOT NULL AUTO_INCREMENT,
  `qtd` DECIMAL(4) NOT NULL,
  `valorVenda` FLOAT NOT NULL,
  `fkProduto` INT NOT NULL,
  `fkVenda` INT NOT NULL,
  PRIMARY KEY (`iditensVendidos`),
  INDEX `fkProduto_idx` (`fkProduto` ASC) VISIBLE,
  INDEX `fkVenda_idx` (`fkVenda` ASC) VISIBLE,
  CONSTRAINT `fkProduto`
    FOREIGN KEY (`fkProduto`)
    REFERENCES `dadosVendas`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkVenda`
    FOREIGN KEY (`fkVenda`)
    REFERENCES `dadosVendas`.`Venda` (`idVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
