-- MySQL Script generated by MySQL Workbench
-- Wed Jun 29 08:50:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema REVENDEDORA2.0
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema REVENDEDORA2.0
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `REVENDEDORA2.0` DEFAULT CHARACTER SET utf8 ;
USE `REVENDEDORA2.0` ;

-- -----------------------------------------------------
-- Table `REVENDEDORA2.0`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `REVENDEDORA2.0`.`Endereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `cep` DECIMAL(3) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  PRIMARY KEY (`idEndereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `REVENDEDORA2.0`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `REVENDEDORA2.0`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` DECIMAL(11) NOT NULL,
  `e-mail` VARCHAR(10) NULL,
  `fkEndereco` INT NOT NULL,
  `numeroCasa` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fkEndereco_idx` (`fkEndereco` ASC) VISIBLE,
  CONSTRAINT `fkEndereco`
    FOREIGN KEY (`fkEndereco`)
    REFERENCES `REVENDEDORA2.0`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `REVENDEDORA2.0`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `REVENDEDORA2.0`.`Telefone` (
  `idTelefone` INT NOT NULL AUTO_INCREMENT,
  `ddd` DECIMAL(2) NOT NULL,
  `numeroTelefone` DECIMAL(9) NOT NULL,
  `fkCliente` INT NOT NULL,
  PRIMARY KEY (`idTelefone`),
  INDEX `fkCliente_idx` (`fkCliente` ASC) VISIBLE,
  CONSTRAINT `fkCliente`
    FOREIGN KEY (`fkCliente`)
    REFERENCES `REVENDEDORA2.0`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `REVENDEDORA2.0`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `REVENDEDORA2.0`.`Empresa` (
  `idEmpresa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `e-mail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEmpresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `REVENDEDORA2.0`.`Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `REVENDEDORA2.0`.`Venda` (
  `idVenda` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `dataPagamento` DATETIME NOT NULL,
  `valorTotal` FLOAT NOT NULL,
  `fkCliente` INT NOT NULL,
  PRIMARY KEY (`idVenda`),
  INDEX `fkCliente_idx` (`fkCliente` ASC) VISIBLE,
  CONSTRAINT `fkCliente`
    FOREIGN KEY (`fkCliente`)
    REFERENCES `REVENDEDORA2.0`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `REVENDEDORA2.0`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `REVENDEDORA2.0`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `tamanho` VARCHAR(45) NOT NULL,
  `cor` VARCHAR(45) NULL,
  `valor` FLOAT NOT NULL,
  `fkEmpresa` INT NOT NULL,
  PRIMARY KEY (`idProduto`),
  INDEX `fkEmpresa_idx` (`fkEmpresa` ASC) VISIBLE,
  CONSTRAINT `fkEmpresa`
    FOREIGN KEY (`fkEmpresa`)
    REFERENCES `REVENDEDORA2.0`.`Empresa` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `REVENDEDORA2.0`.`ItensVendidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `REVENDEDORA2.0`.`ItensVendidos` (
  `idItensVendidos` INT NOT NULL AUTO_INCREMENT,
  `qtd` DECIMAL(10) NOT NULL,
  `valor` FLOAT NOT NULL,
  `fkProduto` INT NOT NULL,
  `fkVenda` INT NOT NULL,
  `checagemProdutos` CHAR(3) NOT NULL,
  PRIMARY KEY (`idItensVendidos`),
  INDEX `fkVenda_idx` (`fkVenda` ASC) VISIBLE,
  INDEX `fkProduto_idx` (`fkProduto` ASC) VISIBLE,
  CONSTRAINT `fkVenda`
    FOREIGN KEY (`fkVenda`)
    REFERENCES `REVENDEDORA2.0`.`Venda` (`idVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkProduto`
    FOREIGN KEY (`fkProduto`)
    REFERENCES `REVENDEDORA2.0`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `REVENDEDORA2.0`.`Troca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `REVENDEDORA2.0`.`Troca` (
  `idTroca` INT NOT NULL AUTO_INCREMENT,
  `fkVenda` INT NOT NULL,
  `fkItensVendidos` INT NOT NULL,
  `dataTroca` DATETIME NOT NULL,
  `checagemTroca` CHAR(3) NOT NULL,
  PRIMARY KEY (`idTroca`),
  INDEX `fkVenda_idx` (`fkVenda` ASC) VISIBLE,
  INDEX `fkItensVendidos_idx` (`fkItensVendidos` ASC) VISIBLE,
  CONSTRAINT `fkVenda`
    FOREIGN KEY (`fkVenda`)
    REFERENCES `REVENDEDORA2.0`.`Venda` (`idVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkItensVendidos`
    FOREIGN KEY (`fkItensVendidos`)
    REFERENCES `REVENDEDORA2.0`.`ItensVendidos` (`idItensVendidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
