-- MySQL Script generated by MySQL Workbench
-- Thu Jun 30 11:28:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BanhoETosa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BanhoETosa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BanhoETosa` DEFAULT CHARACTER SET utf8 ;
USE `BanhoETosa` ;

-- -----------------------------------------------------
-- Table `BanhoETosa`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BanhoETosa`.`Endereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `UF` CHAR(2) NOT NULL,
  `CEP` DECIMAL(8) NOT NULL,
  PRIMARY KEY (`idEndereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BanhoETosa`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BanhoETosa`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` DECIMAL(11) NOT NULL,
  `dataNascimento` DATETIME(6) NOT NULL,
  `fkEndereco` INT NOT NULL,
  `numeroCasa` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fkEndereco_idx` (`fkEndereco` ASC) VISIBLE,
  CONSTRAINT `fkEndereco`
    FOREIGN KEY (`fkEndereco`)
    REFERENCES `BanhoETosa`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BanhoETosa`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BanhoETosa`.`Telefone` (
  `idTelefone` INT NOT NULL AUTO_INCREMENT,
  `numeroTelefone` DECIMAL(9) NOT NULL,
  `ddd` DECIMAL(2) NOT NULL,
  `fkCliente` INT NOT NULL,
  PRIMARY KEY (`idTelefone`),
  INDEX `fkCliente_idx` (`fkCliente` ASC) VISIBLE,
  CONSTRAINT `fkCliente`
    FOREIGN KEY (`fkCliente`)
    REFERENCES `BanhoETosa`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BanhoETosa`.`Racas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BanhoETosa`.`Racas` (
  `idRacas` INT NOT NULL AUTO_INCREMENT,
  `raca` VARCHAR(45) NOT NULL,
  `especie` CHAR(10) NOT NULL,
  `porte` TINYINT NOT NULL,
  PRIMARY KEY (`idRacas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BanhoETosa`.`PET`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BanhoETosa`.`PET` (
  `idPET` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `idade` DECIMAL(2) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `fkCliente` INT NOT NULL,
  `fkRaca` INT NOT NULL,
  PRIMARY KEY (`idPET`),
  INDEX `fkCliente_idx` (`fkCliente` ASC) VISIBLE,
  INDEX `fkRaca_idx` (`fkRaca` ASC) VISIBLE,
  CONSTRAINT `fkCliente`
    FOREIGN KEY (`fkCliente`)
    REFERENCES `BanhoETosa`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkRaca`
    FOREIGN KEY (`fkRaca`)
    REFERENCES `BanhoETosa`.`Racas` (`idRacas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BanhoETosa`.`Agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BanhoETosa`.`Agenda` (
  `idAgenda` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `diaSemana` CHAR(8) NOT NULL,
  `horario` DATETIME NOT NULL,
  `observacoes` LONGTEXT NULL,
  `valorTotal` FLOAT NOT NULL,
  `fkPET` INT NOT NULL,
  PRIMARY KEY (`idAgenda`),
  INDEX `fkPET_idx` (`fkPET` ASC) VISIBLE,
  CONSTRAINT `fkPET`
    FOREIGN KEY (`fkPET`)
    REFERENCES `BanhoETosa`.`PET` (`idPET`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BanhoETosa`.`Servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BanhoETosa`.`Servico` (
  `idServico` INT NOT NULL AUTO_INCREMENT,
  `tiposDoServico` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `valorServicos` FLOAT NOT NULL,
  PRIMARY KEY (`idServico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BanhoETosa`.`ServicosFeitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BanhoETosa`.`ServicosFeitos` (
  `idServicosFeitos` INT NOT NULL AUTO_INCREMENT,
  `formaPagamento` VARCHAR(45) NOT NULL,
  `fkServico` INT NOT NULL,
  `fkAgenda` INT NOT NULL,
  PRIMARY KEY (`idServicosFeitos`),
  INDEX `fkServico_idx` (`fkServico` ASC) VISIBLE,
  INDEX `fkAgenda_idx` (`fkAgenda` ASC) VISIBLE,
  CONSTRAINT `fkServico`
    FOREIGN KEY (`fkServico`)
    REFERENCES `BanhoETosa`.`Servico` (`idServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkAgenda`
    FOREIGN KEY (`fkAgenda`)
    REFERENCES `BanhoETosa`.`Agenda` (`idAgenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
